singleObject:
    path: /single-object
    defaults:
        _controller: 'app_controller:singleObject'

nestedObjects:
    path: /nested-objects
    defaults:
        _controller: 'app_controller:nestedObjects'